### ISSUE TITLE
Link to other resources

### ISSUE THREAD

**Issue by henryiii** [iris-hep/awesome-hep#5]
There should be a link to <https://github.com/hsf-training/PyHEP-resources> (and one from there back to here)

**Comment by jpivarski** [comment]
It was there, but perhaps links to other lists should be bold to stand out. PyHEP-resources needs a link back here, though.

**Comment by henryiii** [comment]
On it!

**Comment by jpivarski** [comment]
Oh, me too. Should I stop?

**Comment by jpivarski** [comment]
I was putting this at the bottom:

```
## More packages

See the [Python section of awesome-hep](https://github.com/iris-hep/awesome-hep#python) for more.
```

and was just combing back here to see how to reference this issue in the commit message.

**Comment by henryiii** [comment]
See https://github.com/hsf-training/PyHEP-resources/pull/16

**Comment by henryiii** [comment]
We could do dual-ing PRs and see which gets accepted. :)

**Comment by jpivarski** [comment]
Nah, make it simple. I'm involved in, like, 20 things right now anyway.  :)
